import EmblemCell from "./EmblemCell";

export const kboTableCol = [
  {
    name: "팀순위",
    cell: (row) => (
      <EmblemCell rank={row.rank} teamId={row.teamId} name={row.name} />
    ),
  },
  { name: "경기", selector: (row) => row.gamesPlayed, center: true },
  { name: "승", selector: (row) => row.wins, center: true },
  { name: "무", selector: (row) => row.draws, center: true },
  { name: "패", selector: (row) => row.losses, center: true },
  { name: "승률", selector: (row) => row.winRate.toFixed(3), center: true },
  { name: "게임차", selector: (row) => row.gamesBehind, center: true },
  { name: "연속", selector: (row) => row.streak, center: true },
  { name: "타율", selector: (row) => row.battingAvg.toFixed(3), center: true },
  { name: "평균자책", selector: (row) => row.era.toFixed(2), center: true },
  { name: "최근 10경기", selector: (row) => row.lastTen, center: true },
];

export const kboTableData = [
  {
    rank: 1,
    teamId: 8,
    name: "한화",
    gamesPlayed: 73,
    wins: 43,
    draws: 1,
    losses: 29,
    winRate: 0.597,
    gamesBehind: 0.0,
    streak: "1승",
    battingAvg: 0.258,
    era: 3.41,
    lastTen: "6승-1무-3패",
  },
  {
    rank: 2,
    teamId: 3,
    name: "LG",
    gamesPlayed: 74,
    wins: 42,
    draws: 2,
    losses: 30,
    winRate: 0.583,
    gamesBehind: 1.0,
    streak: "1승",
    battingAvg: 0.265,
    era: 3.69,
    lastTen: "4승-1무-5패",
  },

  {
    rank: 3,
    teamId: 7,
    name: "롯데",
    gamesPlayed: 75,
    wins: 41,
    draws: 3,
    losses: 31,
    winRate: 0.569,
    gamesBehind: 2.0,
    streak: "4승",
    battingAvg: 0.285,
    era: 4.72,
    lastTen: "7승-0무-3패",
  },
  {
    rank: 4,
    teamId: 1,
    name: "KIA",
    gamesPlayed: 73,
    wins: 38,
    draws: 2,
    losses: 33,
    winRate: 0.535,
    gamesBehind: 4.5,
    streak: "6승",
    battingAvg: 0.255,
    era: 4.15,
    lastTen: "7승-1무-2패",
  },
  {
    rank: 5,
    teamId: 2,
    name: "삼성",
    gamesPlayed: 74,
    wins: 38,
    draws: 1,
    losses: 35,
    winRate: 0.521,
    gamesBehind: 5.5,
    streak: "3패",
    battingAvg: 0.268,
    era: 4.18,
    lastTen: "4승-0무-6패",
  },
  {
    rank: 6,
    teamId: 6,
    name: "SSG",
    gamesPlayed: 73,
    wins: 36,
    draws: 3,
    losses: 34,
    winRate: 0.514,
    gamesBehind: 6.0,
    streak: "1패",
    battingAvg: 0.245,
    era: 3.53,
    lastTen: "4승-1무-5패",
  },

  {
    rank: 7,
    teamId: 5,
    name: "KT",
    gamesPlayed: 75,
    wins: 37,
    draws: 3,
    losses: 35,
    winRate: 0.514,
    gamesBehind: 6.0,
    streak: "1패",
    battingAvg: 0.256,
    era: 3.61,
    lastTen: "4승-0무-6패",
  },
  {
    rank: 8,
    teamId: 9,
    name: "NC",
    gamesPlayed: 71,
    wins: 32,
    draws: 4,
    losses: 35,
    winRate: 0.478,
    gamesBehind: 8.5,
    streak: "1승",
    battingAvg: 0.255,
    era: 4.64,
    lastTen: "6승-0무-4패",
  },

  {
    rank: 9,
    teamId: 4,
    name: "두산",
    gamesPlayed: 74,
    wins: 29,
    draws: 3,
    losses: 42,
    winRate: 0.408,
    gamesBehind: 13.5,
    streak: "1패",
    battingAvg: 0.256,
    era: 4.54,
    lastTen: "4승-0무-6패",
  },

  {
    rank: 10,
    teamId: 10,
    name: "키움",
    gamesPlayed: 76,
    wins: 21,
    draws: 2,
    losses: 53,
    winRate: 0.284,
    gamesBehind: 23.0,
    streak: "2패",
    battingAvg: 0.231,
    era: 5.61,
    lastTen: "1승-1무-8패",
  },
];
