import EmblemCell from "./EmblemCell";

export const kboTableCol = [
  {
    name: "팀순위",
    cell: (row) => (
      <EmblemCell rank={row.rank} teamId={row.teamId} name={row.name} />
    ),
  },
  { name: "경기", selector: (row) => row.gamesPlayed, center: true },
  { name: "승", selector: (row) => row.wins, center: true },
  { name: "무", selector: (row) => row.draws, center: true },
  { name: "패", selector: (row) => row.losses, center: true },
  { name: "승률", selector: (row) => row.winRate.toFixed(3), center: true },
  { name: "게임차", selector: (row) => row.gamesBehind, center: true },
  { name: "연속", selector: (row) => row.streak, center: true },
  { name: "타율", selector: (row) => row.battingAvg.toFixed(3), center: true },
  { name: "평균자책", selector: (row) => row.era.toFixed(2), center: true },
  { name: "최근 10경기", selector: (row) => row.lastTen, center: true },
];

export const kboTableData = [
  {
    rank: 1,
    teamId: 3,
    name: "LG",
    gamesPlayed: 31,
    wins: 20,
    draws: 0,
    losses: 11,
    winRate: 0.645,
    gamesBehind: 0.0,
    streak: "4패",
    battingAvg: 0.262,
    era: 3.2,
    lastTen: "3승-0무-7패",
  },
  {
    rank: 2,
    teamId: 2,
    name: "삼성",
    gamesPlayed: 31,
    wins: 18,
    draws: 1,
    losses: 12,
    winRate: 0.6,
    gamesBehind: 1.5,
    streak: "6승",
    battingAvg: 0.286,
    era: 4.05,
    lastTen: "7승-1무-2패",
  },
  {
    rank: 3,
    teamId: 8,
    name: "한화",
    gamesPlayed: 32,
    wins: 19,
    draws: 0,
    losses: 13,
    winRate: 0.594,
    gamesBehind: 1.5,
    streak: "4승",
    battingAvg: 0.24,
    era: 3.36,
    lastTen: "8승-0무-2패",
  },
  {
    rank: 4,
    teamId: 7,
    name: "롯데",
    gamesPlayed: 32,
    wins: 18,
    draws: 1,
    losses: 13,
    winRate: 0.581,
    gamesBehind: 2.0,
    streak: "2승",
    battingAvg: 0.292,
    era: 4.64,
    lastTen: "7승-0무-3패",
  },
];
