import EmblemCell from "./EmblemCell";

export const kboTableCol = [
  {
    name: "팀순위",
    cell: (row) => (
      <EmblemCell rank={row.rank} teamId={row.teamId} name={row.name} />
    ),
  },
  { name: "경기", selector: (row) => row.gamesPlayed, center: true },
  { name: "승", selector: (row) => row.wins, center: true },
  { name: "무", selector: (row) => row.draws, center: true },
  { name: "패", selector: (row) => row.losses, center: true },
  { name: "승률", selector: (row) => row.winRate.toFixed(3), center: true },
  { name: "게임차", selector: (row) => row.gamesBehind, center: true },
  { name: "연속", selector: (row) => row.streak, center: true },
  { name: "타율", selector: (row) => row.battingAvg.toFixed(3), center: true },
  { name: "평균자책", selector: (row) => row.era.toFixed(2), center: true },
  { name: "최근 10경기", selector: (row) => row.lastTen, center: true },
];

export const kboTableData = [
  {
    rank: 1,
    teamId: 3,
    name: "LG",
    gamesPlayed: 47,
    wins: 31,
    draws: 0,
    losses: 16,
    winRate: 0.66,
    gamesBehind: 0.0,
    streak: "2승",
    battingAvg: 0.267,
    era: 3.38,
    lastTen: "8승-0무-2패",
  },
  {
    rank: 2,
    teamId: 8,
    name: "한화",
    gamesPlayed: 47,
    wins: 29,
    draws: 0,
    losses: 18,
    winRate: 0.617,
    gamesBehind: 2.0,
    streak: "1승",
    battingAvg: 0.25,
    era: 3.19,
    lastTen: "5승-0무-5패",
  },
  {
    rank: 3,
    teamId: 7,
    name: "롯데",
    gamesPlayed: 49,
    wins: 28,
    draws: 2,
    losses: 19,
    winRate: 0.596,
    gamesBehind: 3.0,
    streak: "1패",
    battingAvg: 0.288,
    era: 4.71,
    lastTen: "6승-1무-3패",
  },
  {
    rank: 4,
    teamId: 6,
    name: "SSG",
    gamesPlayed: 42,
    wins: 23,
    draws: 1,
    losses: 22,
    winRate: 0.511,
    gamesBehind: 7.0,
    streak: "3승",
    battingAvg: 0.235,
    era: 3.59,
    lastTen: "7승-0무-3패",
  },
  {
    rank: 5,
    teamId: 1,
    name: "KIA",
    gamesPlayed: 45,
    wins: 22,
    draws: 0,
    losses: 23,
    winRate: 0.489,
    gamesBehind: 8.0,
    streak: "1패",
    battingAvg: 0.245,
    era: 4.52,
    lastTen: "6승-0무-4패",
  },
  {
    rank: 6,
    teamId: 5,
    name: "KT",
    gamesPlayed: 48,
    wins: 22,
    draws: 3,
    losses: 23,
    winRate: 0.489,
    gamesBehind: 8.0,
    streak: "1승",
    battingAvg: 0.244,
    era: 3.47,
    lastTen: "4승-1무-5패",
  },
  {
    rank: 7,
    teamId: 9,
    name: "NC",
    gamesPlayed: 43,
    wins: 20,
    draws: 1,
    losses: 22,
    winRate: 0.476,
    gamesBehind: 8.5,
    streak: "1패",
    battingAvg: 0.25,
    era: 4.91,
    lastTen: "5승-1무-4패",
  },
  {
    rank: 8,
    teamId: 2,
    name: "삼성",
    gamesPlayed: 48,
    wins: 22,
    draws: 1,
    losses: 25,
    winRate: 0.468,
    gamesBehind: 9.0,
    streak: "1승",
    battingAvg: 0.27,
    era: 4.31,
    lastTen: "3승-0무-7패",
  },

  {
    rank: 9,
    teamId: 4,
    name: "두산",
    gamesPlayed: 47,
    wins: 19,
    draws: 2,
    losses: 26,
    winRate: 0.422,
    gamesBehind: 11.0,
    streak: "4패",
    battingAvg: 0.261,
    era: 4.22,
    lastTen: "3승-1무-6패",
  },

  {
    rank: 10,
    teamId: 10,
    name: "키움",
    gamesPlayed: 50,
    wins: 14,
    draws: 0,
    losses: 36,
    winRate: 0.28,
    gamesBehind: 18.5,
    streak: "2패",
    battingAvg: 0.227,
    era: 6.0,
    lastTen: "1승-0무-9패",
  },
];
